-- DC170508: Optimization.

local state_lib_states = state_lib.states
local move_crouch = move.crouch
local move_standing = move.standing
local anim_danger = anim.danger
local anim_free = anim.free

--------------------------------------------------------------------------------

class "eva_state_mgr_bodystate" (property_evaluator)

function eva_state_mgr_bodystate:__init(st) super ()
	self.st = st
end

function eva_state_mgr_bodystate:evaluate()
	local bodystate = state_lib_states[self.st.target_state].bodystate
	return bodystate == nil or bodystate == self.object:target_body_state()
end

--------------------------------------------------------------------------------

class "eva_state_mgr_bodystate_crouch" (property_evaluator)

function eva_state_mgr_bodystate_crouch:__init(st) super ()
	self.st = st
end

function eva_state_mgr_bodystate_crouch:evaluate()
	return state_lib_states[self.st.target_state].bodystate == move_crouch
end

--------------------------------------------------------------------------------

class "eva_state_mgr_bodystate_standing" (property_evaluator)

function eva_state_mgr_bodystate_standing:__init(st) super ()
	self.st = st
end

function eva_state_mgr_bodystate_standing:evaluate()
	return state_lib_states[self.st.target_state].bodystate == move_standing
end

--------------------------------------------------------------------------------

class "eva_state_mgr_bodystate_crouch_now" (property_evaluator)

function eva_state_mgr_bodystate_crouch_now:__init() super ()
--	self.st = st
end

function eva_state_mgr_bodystate_crouch_now:evaluate()
	return self.object:target_body_state() == move_crouch
end

--------------------------------------------------------------------------------

class "eva_state_mgr_bodystate_standing_now" (property_evaluator)

function eva_state_mgr_bodystate_standing_now:__init() super ()
--	self.st = st
end

function eva_state_mgr_bodystate_standing_now:evaluate()
	return self.object:target_body_state() == move_standing
end

--------------------------------------------------------------------------------

class "act_state_mgr_bodystate_crouch" (action_base)

function act_state_mgr_bodystate_crouch:__init() super ()
end

function act_state_mgr_bodystate_crouch:initialize()
	action_base.initialize(self)
	self.object:set_body_state(move_crouch)
end

function act_state_mgr_bodystate_crouch:execute()
	action_base.execute(self)
end

function act_state_mgr_bodystate_crouch:finalize()
	action_base.finalize(self)
end

--------------------------------------------------------------------------------

class "act_state_mgr_bodystate_standing" (action_base)

function act_state_mgr_bodystate_standing:__init() super ()
--	self.st = st
end

function act_state_mgr_bodystate_standing:initialize()
	action_base.initialize(self)
	self.object:set_body_state(move_standing)
end

function act_state_mgr_bodystate_standing:execute()
	action_base.execute(self)
end

function act_state_mgr_bodystate_standing:finalize()
	action_base.finalize(self)
end

--------------------------------------------------------------------------------

class "act_state_mgr_bodystate_crouch_danger" (action_base)

function act_state_mgr_bodystate_crouch_danger:__init() super ()
end

function act_state_mgr_bodystate_crouch_danger:initialize()
	action_base.initialize(self)
	local sobj = self.object
	sobj:set_mental_state(anim_danger)
	sobj:set_body_state(move_crouch)
end

function act_state_mgr_bodystate_crouch_danger:execute()
	action_base.execute(self)
end

function act_state_mgr_bodystate_crouch_danger:finalize()
	action_base.finalize(self)
end

--------------------------------------------------------------------------------

class "act_state_mgr_bodystate_standing_free" (action_base)

function act_state_mgr_bodystate_standing_free:__init() super ()
--	self.st = st
end

function act_state_mgr_bodystate_standing_free:initialize()
	action_base.initialize(self)
	local sobj = self.object
	sobj:set_body_state(move_standing)
	sobj:set_mental_state(anim_free)
end

function act_state_mgr_bodystate_standing_free:execute()
	action_base.execute(self)
end

function act_state_mgr_bodystate_standing_free:finalize()
	action_base.finalize(self)
end